// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OM.MFPTrackerV1.Data;

#nullable disable

namespace OM.MFPTrackerV1.Data.Migrations
{
    [DbContext(typeof(MFPTrackerDbContext))]
    [Migration("20260404011819_specialEvents")]
    partial class specialEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.AMC", b =>
                {
                    b.Property<int>("AMCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AMCName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("AMCId");

                    b.HasIndex("AMCName")
                        .IsUnique();

                    b.ToTable("TAMC", null, t =>
                        {
                            t.HasCheckConstraint("CK_AMC_AMCName_Len", "length(AMCName) BETWEEN 2 AND 100");
                        });

                    b.HasData(
                        new
                        {
                            AMCId = 1,
                            AMCName = "Axis Mutual Fund"
                        },
                        new
                        {
                            AMCId = 2,
                            AMCName = "Bandhan Mutual Fund"
                        },
                        new
                        {
                            AMCId = 3,
                            AMCName = "Canara Robeco Mutual Fund"
                        },
                        new
                        {
                            AMCId = 4,
                            AMCName = "Kotak Mutual Fund"
                        },
                        new
                        {
                            AMCId = 5,
                            AMCName = "Mirae Asset Mutual Fund"
                        },
                        new
                        {
                            AMCId = 6,
                            AMCName = "Nippon India Mutual Fund"
                        },
                        new
                        {
                            AMCId = 7,
                            AMCName = "Parag Parikh Mutual Fund"
                        },
                        new
                        {
                            AMCId = 8,
                            AMCName = "SBI Mutual Fund"
                        },
                        new
                        {
                            AMCId = 9,
                            AMCName = "HDFC Mutual Fund"
                        },
                        new
                        {
                            AMCId = 10,
                            AMCName = "TATA Mutual Fund"
                        },
                        new
                        {
                            AMCId = 11,
                            AMCName = "ICICI Mutual Fund"
                        },
                        new
                        {
                            AMCId = 12,
                            AMCName = "UTI Mutual Fund"
                        },
                        new
                        {
                            AMCId = 13,
                            AMCName = "Aditya Birla Sun Life Mutual Fund"
                        },
                        new
                        {
                            AMCId = 14,
                            AMCName = "Jio BlackRock Mutual Fund"
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Folio", b =>
                {
                    b.Property<int>("FolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AMCId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachedBank")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("FolioHolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolioNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("FolioPurpose")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FolioId");

                    b.HasIndex("AMCId");

                    b.HasIndex("FolioHolderId");

                    b.HasIndex("FolioNumber")
                        .IsUnique();

                    b.ToTable("TFolio", null, t =>
                        {
                            t.HasCheckConstraint("CK_Folio_Bank_Len", "AttachedBank IS NULL OR length(AttachedBank) <= 50");

                            t.HasCheckConstraint("CK_Folio_Number_Len", "length(FolioNumber) BETWEEN 5 AND 50");

                            t.HasCheckConstraint("CK_Folio_Purpose_Len", "FolioPurpose IS NULL OR length(FolioPurpose) <= 100");
                        });

                    b.HasData(
                        new
                        {
                            FolioId = 1,
                            AMCId = 9,
                            AttachedBank = "JAG IDFC NRO",
                            FolioHolderId = 3,
                            FolioNumber = "37959966",
                            FolioPurpose = "Long term Portfolio",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioId = 2,
                            AMCId = 6,
                            AttachedBank = "DK HDFC NRO",
                            FolioHolderId = 2,
                            FolioNumber = "499183354147",
                            FolioPurpose = "Small can investment - experiment",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioId = 3,
                            AMCId = 7,
                            AttachedBank = "DK HDFC NRO",
                            FolioHolderId = 2,
                            FolioNumber = "10121489",
                            FolioPurpose = "Long term Investment",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioId = 4,
                            AMCId = 7,
                            AttachedBank = "DK KOTAK NRE",
                            FolioHolderId = 2,
                            FolioNumber = "10510544",
                            FolioPurpose = "Long term Repatriate Inv",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioId = 5,
                            AMCId = 7,
                            AttachedBank = "DK IDFC NRO",
                            FolioHolderId = 2,
                            FolioNumber = "17412588",
                            FolioPurpose = "Long term Repatriate Inv",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioId = 6,
                            AMCId = 7,
                            AttachedBank = "DK IDFC NRO",
                            FolioHolderId = 3,
                            FolioNumber = "17713086",
                            FolioPurpose = "Long term Repatriate Inv",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.FolioHolder", b =>
                {
                    b.Property<int>("FolioHolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FolioHolderId");

                    b.HasIndex("Signature")
                        .IsUnique();

                    b.HasIndex("FirstName", "LastName", "DateOfBirth")
                        .IsUnique();

                    b.ToTable("TFolioHolder", (string)null);

                    b.HasData(
                        new
                        {
                            FolioHolderId = 1,
                            DateOfBirth = new DateTime(1977, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rupam",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "RS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioHolderId = 2,
                            DateOfBirth = new DateTime(1973, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Deepak",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DK",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioHolderId = 3,
                            DateOfBirth = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jagruti",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "JS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioHolderId = 4,
                            DateOfBirth = new DateTime(2010, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Divyam",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DIVS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioHolderId = 5,
                            DateOfBirth = new DateTime(1951, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "DP",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "PAA",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioHolderId = 6,
                            DateOfBirth = new DateTime(1961, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Radha",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Devi",
                            Signature = "MAA",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.FolioOwner", b =>
                {
                    b.Property<int>("FolioOwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("FolioOwnerId");

                    b.HasIndex("Signature")
                        .IsUnique();

                    b.HasIndex("FirstName", "LastName", "DateOfBirth")
                        .IsUnique();

                    b.ToTable("TFolioOwner", (string)null);

                    b.HasData(
                        new
                        {
                            FolioOwnerId = 1,
                            DateOfBirth = new DateTime(2002, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "AAA",
                            LastName = "Delete me",
                            Signature = "DK"
                        },
                        new
                        {
                            FolioOwnerId = 2,
                            DateOfBirth = new DateTime(2010, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "BBB",
                            LastName = "Delete me",
                            Signature = "RS"
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Fund", b =>
                {
                    b.Property<int>("FundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AMCId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsNavAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTransactionAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("MFCatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FundId");

                    b.HasIndex("AMCId");

                    b.HasIndex("FundName");

                    b.HasIndex("ISIN")
                        .IsUnique();

                    b.HasIndex("MFCatId");

                    b.HasIndex("AMCId", "SchemeCode")
                        .IsUnique();

                    b.ToTable("TFund", null, t =>
                        {
                            t.HasCheckConstraint("CK_Fund_FundName_Len", "length(FundName) BETWEEN 5 AND 100");

                            t.HasCheckConstraint("CK_Fund_ISIN_Len", "length(ISIN) BETWEEN 1 AND 20");

                            t.HasCheckConstraint("CK_Fund_SchemeCode_Len", "length(SchemeCode) BETWEEN 1 AND 20");
                        });

                    b.HasData(
                        new
                        {
                            FundId = 1,
                            AMCId = 7,
                            FundName = "Parag Parikh Flexi Cap Fund - Direct Plan - Growth",
                            ISIN = "INF879O01027",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 2,
                            SchemeCode = "122639",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 2,
                            AMCId = 7,
                            FundName = "Parag Parikh Dynamic Asset Allocation Fund - Direct Plan Growth",
                            ISIN = "INF879O01266",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 1,
                            SchemeCode = "152468",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 3,
                            AMCId = 1,
                            FundName = "Axis Small Cap Fund - Direct Plan - Growth",
                            ISIN = "INF846K01K35",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 6,
                            SchemeCode = "125354",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 4,
                            AMCId = 3,
                            FundName = "Canara Robeco SMALL CAP Fund - Direct Plan - Growth",
                            ISIN = "INF760K01JC6",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 17,
                            SchemeCode = "146130",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 5,
                            AMCId = 3,
                            FundName = "Canara Robeco LARGE AND MID CAP Fund - Direct Plan - Growth",
                            ISIN = "INF760K01EI4",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 3,
                            SchemeCode = "118278",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 6,
                            AMCId = 3,
                            FundName = "Canara Robeco Value Fund - Direct Plan - Growth",
                            ISIN = "INF760K01JW4",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 9,
                            SchemeCode = "149085",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 7,
                            AMCId = 4,
                            FundName = "Kotak Large & Midcap Fund - Direct- Growth",
                            ISIN = "INF174K01LF9",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 3,
                            SchemeCode = "120158",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 8,
                            AMCId = 5,
                            FundName = "Mirae Asset Large & Midcap Fund - Direct Plan - Growth",
                            ISIN = "INF769K01BI1",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 3,
                            SchemeCode = "118834",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 9,
                            AMCId = 5,
                            FundName = "Mirae Asset ELSS Tax Saver Fund - Direct Plan - Growth",
                            ISIN = "INF769K01DM9",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 7,
                            SchemeCode = "135781",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 10,
                            AMCId = 6,
                            FundName = "Nippon India Small Cap Fund - Direct Plan - Growth",
                            ISIN = "INF204K01K15",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 6,
                            SchemeCode = "118778",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 11,
                            AMCId = 8,
                            FundName = "SBI Large Cap Fund - Direct Plan - Growth",
                            ISIN = "INF200K01QX4",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 4,
                            SchemeCode = "119598",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 12,
                            AMCId = 8,
                            FundName = "SBI Small Cap Fund - Direct Plan - Growth",
                            ISIN = "INF200K01T51",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 6,
                            SchemeCode = "125497",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 13,
                            AMCId = 10,
                            FundName = "Tata Retirement Savings Fund- Progressive Plan - Direct Plan - Growth",
                            ISIN = "INF277K01QO1",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 2,
                            SchemeCode = "119251",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 14,
                            AMCId = 10,
                            FundName = "Tata S&P BSE Sensex Index Fund - Direct Plan",
                            ISIN = "INF277K01PK1",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 4,
                            SchemeCode = "119287",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 15,
                            AMCId = 2,
                            FundName = "BANDHAN Small Cap Fund - Regular Plan - Growth",
                            ISIN = "INF194KB1AJ8",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 6,
                            SchemeCode = "147944",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 16,
                            AMCId = 9,
                            FundName = "HDFC Small Cap Fund - Growth Option - Direct Plan",
                            ISIN = "INF179KA1RW5",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 6,
                            SchemeCode = "130503",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 17,
                            AMCId = 9,
                            FundName = "HDFC Gold ETF Fund of Fund - Direct Plan",
                            ISIN = "INF179K01VX0",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 19,
                            SchemeCode = "119132",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.FundNav", b =>
                {
                    b.Property<int>("FundNavId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("NavDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NavValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("FundNavId");

                    b.HasIndex("FundId", "NavDate")
                        .IsUnique();

                    b.ToTable("TFundNav", null, t =>
                        {
                            t.HasCheckConstraint("CK_FundNav_NavValue_Positive", "NavValue > 0.0");
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.MFCategory", b =>
                {
                    b.Property<int>("MFCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("MFCatId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("TMFCategory", null, t =>
                        {
                            t.HasCheckConstraint("CK_MFCat_Name_Len", "length(CategoryName) BETWEEN 3 AND 50");
                        });

                    b.HasData(
                        new
                        {
                            MFCatId = 1,
                            CategoryName = "Equity - Multi Cap"
                        },
                        new
                        {
                            MFCatId = 2,
                            CategoryName = "Equity - Flexi Cap"
                        },
                        new
                        {
                            MFCatId = 3,
                            CategoryName = "Equity - Large Mid Cap"
                        },
                        new
                        {
                            MFCatId = 4,
                            CategoryName = "Equity - Large Cap"
                        },
                        new
                        {
                            MFCatId = 5,
                            CategoryName = "Equity - Mid Cap"
                        },
                        new
                        {
                            MFCatId = 6,
                            CategoryName = "Equity - Small Cap"
                        },
                        new
                        {
                            MFCatId = 7,
                            CategoryName = "Equity - ELSS Cap"
                        },
                        new
                        {
                            MFCatId = 8,
                            CategoryName = "Equity - Dividend Yield MF"
                        },
                        new
                        {
                            MFCatId = 9,
                            CategoryName = "Equity - Value Oriented MF"
                        },
                        new
                        {
                            MFCatId = 10,
                            CategoryName = "Equity - Sectoral MF"
                        },
                        new
                        {
                            MFCatId = 11,
                            CategoryName = "Debt - Liquid"
                        },
                        new
                        {
                            MFCatId = 12,
                            CategoryName = "Debt - Corporate Bonds MF"
                        },
                        new
                        {
                            MFCatId = 13,
                            CategoryName = "Debt - Dynamic Bond Debt MF"
                        },
                        new
                        {
                            MFCatId = 14,
                            CategoryName = "Debt - Ultra Short Term MF"
                        },
                        new
                        {
                            MFCatId = 15,
                            CategoryName = "Hybrid - Aggressive"
                        },
                        new
                        {
                            MFCatId = 16,
                            CategoryName = "Hybrid - Balanced"
                        },
                        new
                        {
                            MFCatId = 17,
                            CategoryName = "Hybrid - Equity Savings"
                        },
                        new
                        {
                            MFCatId = 18,
                            CategoryName = "Hybrid - Dynamic Asset allocation"
                        },
                        new
                        {
                            MFCatId = 19,
                            CategoryName = "Commodities - Gold MF (ETF)"
                        },
                        new
                        {
                            MFCatId = 20,
                            CategoryName = "Commodities - Silver MF (ETF)"
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.MutualFundTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("FolioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("NAV")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TxnType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Units")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("TransactionId");

                    b.HasIndex("FundId");

                    b.HasIndex("TxnType");

                    b.HasIndex("FolioId", "TransactionDate");

                    b.ToTable("TMutualFundTransaction", null, t =>
                        {
                            t.HasCheckConstraint("CK_MFTransaction_AmountPaid_Positive", "AmountPaid >= 0.0");

                            t.HasCheckConstraint("CK_MFTransaction_NAV_Positive", "NAV >= 0.0");

                            t.HasCheckConstraint("CK_MFTransaction_Units_Positive", "Units >= 0.0");
                        });

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AmountPaid = 4256.18m,
                            FolioId = 1,
                            FundId = 1,
                            InDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NAV = 42.3500m,
                            Note = "Lumpsum investment",
                            ReferenceNo = "TXN1001",
                            Source = "Initial Purchase",
                            TransactionDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TxnType = 1,
                            Units = 100.500000m,
                            UpdateDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 2,
                            AmountPaid = 2210.00m,
                            FolioId = 1,
                            FundId = 1,
                            InDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NAV = 44.2000m,
                            Note = "Monthly SIP",
                            ReferenceNo = "TXN1002",
                            Source = "SIP",
                            TransactionDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TxnType = 1,
                            Units = 50.000000m,
                            UpdateDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 3,
                            AmountPaid = 4899.78m,
                            FolioId = 1,
                            FundId = 2,
                            InDate = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NAV = 65.1000m,
                            Note = "Diversification",
                            ReferenceNo = "TXN1003",
                            Source = "Lumpsum",
                            TransactionDate = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TxnType = 1,
                            Units = 75.250000m,
                            UpdateDate = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.SpecialEvent", b =>
                {
                    b.Property<int>("SpecialEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int?>("FundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Info")
                        .UseCollation("NOCASE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("SpecialEventId");

                    b.HasIndex("EventDate");

                    b.HasIndex("EventType");

                    b.HasIndex("FundId");

                    b.ToTable("TSpecialEvent", (string)null);

                    b.HasData(
                        new
                        {
                            SpecialEventId = 1,
                            Description = "Global equity markets corrected sharply due to COVID-19 pandemic fears.",
                            EventDate = new DateTime(2020, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Market",
                            InDate = new DateTime(2020, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Critical",
                            Title = "COVID-19 Market Crash"
                        },
                        new
                        {
                            SpecialEventId = 2,
                            Description = "Government reintroduced 10% LTCG tax on equity gains exceeding ₹1L.",
                            EventDate = new DateTime(2018, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Regulatory",
                            InDate = new DateTime(2018, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Warning",
                            Title = "Reintroduction of LTCG Tax on Equity"
                        },
                        new
                        {
                            SpecialEventId = 3,
                            Description = "RBI increased repo rate to curb inflation, impacting debt fund NAVs.",
                            EventDate = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Macro",
                            InDate = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Info",
                            Title = "RBI Begins Rate Hike Cycle"
                        },
                        new
                        {
                            SpecialEventId = 4,
                            Description = "Annual Union Budget presented with implications for equity and debt markets.",
                            EventDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Market",
                            InDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Info",
                            Title = "Union Budget Announcement"
                        },
                        new
                        {
                            SpecialEventId = 5,
                            Description = "Expense ratio revised by fund house.",
                            EventDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Fund",
                            FundId = 1,
                            InDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Severity = "Info",
                            Title = "Expense Ratio Revision"
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Folio", b =>
                {
                    b.HasOne("OM.MFPTrackerV1.Data.Models.AMC", "AMC")
                        .WithMany("Folios")
                        .HasForeignKey("AMCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OM.MFPTrackerV1.Data.Models.FolioHolder", "Holder")
                        .WithMany("Folios")
                        .HasForeignKey("FolioHolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AMC");

                    b.Navigation("Holder");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Fund", b =>
                {
                    b.HasOne("OM.MFPTrackerV1.Data.Models.AMC", "AMC")
                        .WithMany("Funds")
                        .HasForeignKey("AMCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OM.MFPTrackerV1.Data.Models.MFCategory", "Category")
                        .WithMany("Funds")
                        .HasForeignKey("MFCatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AMC");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.FundNav", b =>
                {
                    b.HasOne("OM.MFPTrackerV1.Data.Models.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.MutualFundTransaction", b =>
                {
                    b.HasOne("OM.MFPTrackerV1.Data.Models.Folio", "Folio")
                        .WithMany()
                        .HasForeignKey("FolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OM.MFPTrackerV1.Data.Models.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Folio");

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.SpecialEvent", b =>
                {
                    b.HasOne("OM.MFPTrackerV1.Data.Models.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.AMC", b =>
                {
                    b.Navigation("Folios");

                    b.Navigation("Funds");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.FolioHolder", b =>
                {
                    b.Navigation("Folios");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.MFCategory", b =>
                {
                    b.Navigation("Funds");
                });
#pragma warning restore 612, 618
        }
    }
}
