// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OM.MFPTrackerV1.Data;

#nullable disable

namespace OM.MFPTrackerV1.Data.Migrations
{
    [DbContext(typeof(MFPTrackerDbContext))]
    [Migration("20260312050308_Foliorelationshipfixed")]
    partial class Foliorelationshipfixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Folio", b =>
                {
                    b.Property<int>("FolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachedBank")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("FolioHolderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FolioHolderId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolioNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("FolioPurpose")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("FundId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FundId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FolioId");

                    b.HasIndex("FolioHolderId1");

                    b.HasIndex("FundId");

                    b.HasIndex("FundId1");

                    b.HasIndex("FolioHolderId", "FundId", "FolioNumber")
                        .IsUnique();

                    b.ToTable("TFolio", (string)null);

                    b.HasData(
                        new
                        {
                            FolioId = 1,
                            FolioHolderId = 1,
                            FolioNumber = "FOLIO123",
                            FolioPurpose = "Investment in Axis Small Cap Fund",
                            FundId = 1,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioId = 2,
                            FolioHolderId = 2,
                            FolioNumber = "FOLIO456",
                            FolioPurpose = "Investment in Axis Small Cap Fund",
                            FundId = 1,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioId = 3,
                            FolioHolderId = 3,
                            FolioNumber = "FOLIO789",
                            FolioPurpose = "Investment in Bandhan Small Cap Fund",
                            FundId = 2,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.FolioHolder", b =>
                {
                    b.Property<int>("FolioHolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FolioHolderId");

                    b.HasIndex("FirstName")
                        .IsUnique();

                    b.HasIndex("FolioHolderId");

                    b.HasIndex("Signature")
                        .IsUnique();

                    b.HasIndex("FirstName", "LastName", "DateOfBirth")
                        .IsUnique();

                    b.ToTable("TFolioHolder", (string)null);

                    b.HasData(
                        new
                        {
                            FolioHolderId = 1,
                            DateOfBirth = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rupam",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "RS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioHolderId = 2,
                            DateOfBirth = new DateTime(1981, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Deepak",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DK",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioHolderId = 3,
                            DateOfBirth = new DateTime(1974, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jagruti",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "JS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioHolderId = 4,
                            DateOfBirth = new DateTime(2001, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Divyam",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioHolderId = 5,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Durga Prasad",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DP",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioHolderId = 6,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Radha",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "RD",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Fund", b =>
                {
                    b.Property<int>("FundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AMCName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsNavAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTransactionAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("MFCatId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MFCategoryMFCatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FundId");

                    b.HasIndex("AMCName");

                    b.HasIndex("FundName")
                        .IsUnique();

                    b.HasIndex("ISIN")
                        .IsUnique();

                    b.HasIndex("MFCatId");

                    b.HasIndex("MFCategoryMFCatId");

                    b.HasIndex("SchemeCode")
                        .IsUnique();

                    b.ToTable("TFund", (string)null);

                    b.HasData(
                        new
                        {
                            FundId = 1,
                            AMCName = "AXIS MF",
                            FundName = "AXIS SMALL CAP Fund - DIRECT PLAN - GROWTH",
                            ISIN = "INF846K01K35",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 1,
                            SchemeCode = "125354",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 2,
                            AMCName = "BANDHAN MF",
                            FundName = "BANDHAN SMALL CAP FUND - REGULAR PLAN GROWTH",
                            ISIN = "INF194KB1AJ8",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 1,
                            SchemeCode = "147944",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.MFCategory", b =>
                {
                    b.Property<int>("MFCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("MFCatId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("TMFCategory", (string)null);

                    b.HasData(
                        new
                        {
                            MFCatId = 1,
                            CategoryName = "Equity-Multi Cap "
                        },
                        new
                        {
                            MFCatId = 2,
                            CategoryName = "Equity-Flexi Cap"
                        },
                        new
                        {
                            MFCatId = 3,
                            CategoryName = "Equity-Large & MidCap"
                        },
                        new
                        {
                            MFCatId = 4,
                            CategoryName = "Equity-Large Cap"
                        },
                        new
                        {
                            MFCatId = 5,
                            CategoryName = "Equity-Mid Cap"
                        },
                        new
                        {
                            MFCatId = 6,
                            CategoryName = "Equity-Small Cap"
                        },
                        new
                        {
                            MFCatId = 7,
                            CategoryName = "Equity-ELSS"
                        },
                        new
                        {
                            MFCatId = 8,
                            CategoryName = "Equity-Dividend Yield"
                        },
                        new
                        {
                            MFCatId = 9,
                            CategoryName = "Equity-Contra"
                        },
                        new
                        {
                            MFCatId = 10,
                            CategoryName = "Equity-Sectoral"
                        },
                        new
                        {
                            MFCatId = 11,
                            CategoryName = "Equity-Value Oriented"
                        },
                        new
                        {
                            MFCatId = 12,
                            CategoryName = "Debt-Liquid Fund"
                        },
                        new
                        {
                            MFCatId = 13,
                            CategoryName = "Debt-Overnight Funds"
                        },
                        new
                        {
                            MFCatId = 14,
                            CategoryName = "Debt-Money Market Funds"
                        },
                        new
                        {
                            MFCatId = 15,
                            CategoryName = "Debt-Corporate Bond Funds"
                        },
                        new
                        {
                            MFCatId = 16,
                            CategoryName = "Debt-Gilt Funds"
                        },
                        new
                        {
                            MFCatId = 17,
                            CategoryName = "Hybrid Fund"
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Folio", b =>
                {
                    b.HasOne("OM.MFPTrackerV1.Data.Models.FolioHolder", "Holder")
                        .WithMany()
                        .HasForeignKey("FolioHolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OM.MFPTrackerV1.Data.Models.FolioHolder", null)
                        .WithMany("Folios")
                        .HasForeignKey("FolioHolderId1");

                    b.HasOne("OM.MFPTrackerV1.Data.Models.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OM.MFPTrackerV1.Data.Models.Fund", null)
                        .WithMany("Folios")
                        .HasForeignKey("FundId1");

                    b.Navigation("Fund");

                    b.Navigation("Holder");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Fund", b =>
                {
                    b.HasOne("OM.MFPTrackerV1.Data.Models.MFCategory", "Category")
                        .WithMany()
                        .HasForeignKey("MFCatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OM.MFPTrackerV1.Data.Models.MFCategory", null)
                        .WithMany("Funds")
                        .HasForeignKey("MFCategoryMFCatId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.FolioHolder", b =>
                {
                    b.Navigation("Folios");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Fund", b =>
                {
                    b.Navigation("Folios");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.MFCategory", b =>
                {
                    b.Navigation("Funds");
                });
#pragma warning restore 612, 618
        }
    }
}
