// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OM.MFPTrackerV1.Data;

#nullable disable

namespace OM.MFPTrackerV1.Data.Migrations
{
    [DbContext(typeof(MFPTrackerDbContext))]
    [Migration("20260312130302_redesignDB")]
    partial class redesignDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.AMC", b =>
                {
                    b.Property<int>("AMCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AMCName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("AMCId");

                    b.HasIndex("AMCName")
                        .IsUnique();

                    b.ToTable("TAMC", null, t =>
                        {
                            t.HasCheckConstraint("CK_AMC_AMCName_Len", "length(AMCName) BETWEEN 2 AND 100");
                        });

                    b.HasData(
                        new
                        {
                            AMCId = 1,
                            AMCName = "Axis Mutual Fund"
                        },
                        new
                        {
                            AMCId = 2,
                            AMCName = "Bandhan Mutual Fund"
                        },
                        new
                        {
                            AMCId = 3,
                            AMCName = "HDFC Mutual Fund"
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Folio", b =>
                {
                    b.Property<int>("FolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AMCId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachedBank")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("FolioHolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolioNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("FolioPurpose")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FolioId");

                    b.HasIndex("AMCId");

                    b.HasIndex("FolioHolderId");

                    b.HasIndex("AMCId", "FolioNumber")
                        .IsUnique();

                    b.ToTable("TFolio", null, t =>
                        {
                            t.HasCheckConstraint("CK_Folio_Bank_Len", "AttachedBank IS NULL OR length(AttachedBank) <= 50");

                            t.HasCheckConstraint("CK_Folio_Number_Len", "length(FolioNumber) BETWEEN 5 AND 50");

                            t.HasCheckConstraint("CK_Folio_Purpose_Len", "FolioPurpose IS NULL OR length(FolioPurpose) <= 100");
                        });

                    b.HasData(
                        new
                        {
                            FolioId = 1,
                            AMCId = 1,
                            FolioHolderId = 2,
                            FolioNumber = "1234567",
                            FolioPurpose = "Investment Portfolio",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioId = 2,
                            AMCId = 2,
                            FolioHolderId = 1,
                            FolioNumber = "2233445",
                            FolioPurpose = "Family Holdings",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.FolioHolder", b =>
                {
                    b.Property<int>("FolioHolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FolioHolderId");

                    b.HasIndex("Signature")
                        .IsUnique();

                    b.HasIndex("FirstName", "LastName", "DateOfBirth")
                        .IsUnique();

                    b.ToTable("TFolioHolder", null, t =>
                        {
                            t.HasCheckConstraint("CK_FH_FirstName_Len", "length(FirstName) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_FH_LastName_Len", "length(LastName) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_FH_Signature_Len", "length(Signature) BETWEEN 2 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            FolioHolderId = 1,
                            DateOfBirth = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rupam",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "RS",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FolioHolderId = 2,
                            DateOfBirth = new DateTime(1981, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Deepak",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaw",
                            Signature = "DK",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Fund", b =>
                {
                    b.Property<int>("FundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AMCId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AMCName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsNavAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTransactionAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("MFCatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("FundId");

                    b.HasIndex("AMCId");

                    b.HasIndex("FundName")
                        .IsUnique();

                    b.HasIndex("ISIN")
                        .IsUnique();

                    b.HasIndex("MFCatId");

                    b.HasIndex("SchemeCode")
                        .IsUnique();

                    b.ToTable("TFund", null, t =>
                        {
                            t.HasCheckConstraint("CK_Fund_AMCName_Len", "length(AMCName) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Fund_FundName_Len", "length(FundName) BETWEEN 5 AND 100");

                            t.HasCheckConstraint("CK_Fund_ISIN_Len", "length(ISIN) BETWEEN 1 AND 20");

                            t.HasCheckConstraint("CK_Fund_SchemeCode_Len", "length(SchemeCode) BETWEEN 1 AND 20");
                        });

                    b.HasData(
                        new
                        {
                            FundId = 1,
                            AMCId = 1,
                            AMCName = "Axis MF",
                            FundName = "Axis Small Cap Fund - Direct Plan - Growth",
                            ISIN = "INF846K01K35",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 1,
                            SchemeCode = "125354",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            FundId = 2,
                            AMCId = 2,
                            AMCName = "Bandhan MF",
                            FundName = "Bandhan Small Cap Fund - Regular Plan - Growth",
                            ISIN = "INF194KB1AJ8",
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNavAllowed = true,
                            IsTransactionAllowed = true,
                            MFCatId = 1,
                            SchemeCode = "147944",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.MFCategory", b =>
                {
                    b.Property<int>("MFCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("MFCatId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("TMFCategory", null, t =>
                        {
                            t.HasCheckConstraint("CK_MFCat_Name_Len", "length(CategoryName) BETWEEN 3 AND 50");
                        });

                    b.HasData(
                        new
                        {
                            MFCatId = 1,
                            CategoryName = "Equity - Small Cap"
                        },
                        new
                        {
                            MFCatId = 2,
                            CategoryName = "Equity - Multi Cap"
                        },
                        new
                        {
                            MFCatId = 3,
                            CategoryName = "Debt - Liquid"
                        },
                        new
                        {
                            MFCatId = 4,
                            CategoryName = "Hybrid - Aggressive"
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.MutualFundTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FolioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("NAV")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("TxnType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Units")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("FolioId");

                    b.HasIndex("FundId");

                    b.ToTable("TMFTransaction", null, t =>
                        {
                            t.HasCheckConstraint("CK_Txn_Note_Len", "Note IS NULL OR length(Note) <= 100");

                            t.HasCheckConstraint("CK_Txn_Source_Len", "Source IS NULL OR length(Source) <= 50");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 480m,
                            Date = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FolioId = 1,
                            FundId = 1,
                            InDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NAV = 12m,
                            Source = "Kotak Bank NRO",
                            TxnType = 1,
                            Units = 40m,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Folio", b =>
                {
                    b.HasOne("OM.MFPTrackerV1.Data.Models.AMC", "AMC")
                        .WithMany("Folios")
                        .HasForeignKey("AMCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OM.MFPTrackerV1.Data.Models.FolioHolder", "Holder")
                        .WithMany("Folios")
                        .HasForeignKey("FolioHolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AMC");

                    b.Navigation("Holder");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.Fund", b =>
                {
                    b.HasOne("OM.MFPTrackerV1.Data.Models.AMC", "AMC")
                        .WithMany("Funds")
                        .HasForeignKey("AMCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OM.MFPTrackerV1.Data.Models.MFCategory", "Category")
                        .WithMany("Funds")
                        .HasForeignKey("MFCatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AMC");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.MutualFundTransaction", b =>
                {
                    b.HasOne("OM.MFPTrackerV1.Data.Models.Folio", "Folio")
                        .WithMany()
                        .HasForeignKey("FolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OM.MFPTrackerV1.Data.Models.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folio");

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.AMC", b =>
                {
                    b.Navigation("Folios");

                    b.Navigation("Funds");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.FolioHolder", b =>
                {
                    b.Navigation("Folios");
                });

            modelBuilder.Entity("OM.MFPTrackerV1.Data.Models.MFCategory", b =>
                {
                    b.Navigation("Funds");
                });
#pragma warning restore 612, 618
        }
    }
}
